import type { Metadata } from 'next'
import { Geist_Mono, Coiny } from 'next/font/google'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import Cursor from '@/components/Layout/Cursor'
import MotionMain from '@/components/Layout/MotionMain'
import '@/lib/gsap'
import './globals.css'

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const geistCoiny = Coiny({
  variable: '--font-coiny',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'BBB_CCC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const menuItems = [
    {
      name: 'DEMO',
      href: '/demo',
      children: [{ name: '森朗醫學診所', href: '/demo/sunclinic' }],
    },
  ]

  return (
    <html lang="en">
      <body className={`${geistCoiny.variable} ${geistMono.variable} flex flex-col items-center antialiased`}>
        <Cursor />
        <Header menuItems={menuItems} />
        <div className="mx-auto px-5 pt-20">
          <MotionMain>{children}</MotionMain>
        </div>
        <Footer />
      </body>
    </html>
  )
}
