import type { Metadata } from 'next'
import { Geist, Geist_Mono, Roboto } from 'next/font/google'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import MotionMain from '@/components/Layout/MotionMain'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const geistRoboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const menuItems = [
    {
      name: 'Demo',
      href: '/demo',
      children: [{ name: '森朗醫學診所', href: '/demo/sunclinic' }],
    },
  ]

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${geistRoboto.variable} antialiased`}>
        <Header menuItems={menuItems} />
        <div className="min-h-[calc(100vh-160px)]">
          <MotionMain>{children}</MotionMain>
        </div>
        <Footer />
      </body>
    </html>
  )
}
